Repository lmachens/game-ticker, pull requests merged in 2021-07, with the labels that each got.

#33 🔧 Use local debugger
  dist/overwolf/manifest.json
Labels: development

#34 ✨ Restore desktop window on app launch triggered
  src/app/background.tsx
  src/app/components/AppHeader/AppHeader.tsx
  src/app/utils/overwolf.ts
  src/app/utils/windows.ts
Labels: development, enhancement

#35 ✨ Add Match components
  .stylelintrc.json
  src/app/components/MatchDetails/MatchDetails.examples.tsx
  src/app/components/MatchDetails/MatchDetails.module.css
  src/app/components/MatchDetails/MatchDetails.tsx
  src/app/components/MatchItem/MatchItem.examples.tsx
  src/app/components/MatchItem/MatchItem.module.css
  src/app/components/MatchItem/MatchItem.tsx
  src/app/components/examples.ts
  src/app/globals.css
  src/app/hooks/useGameInfo.ts
  src/app/utils.module.css
  src/app/utils/games.ts
Labels: component

#41 ✨ Add feed and details to desktop window
  samples.http
  src/app/App.module.css
  src/app/App.tsx
  src/app/components/AppHeader/AppHeader.tsx
  src/app/components/Feed/Feed.examples.tsx
  src/app/components/Feed/Feed.module.css
  src/app/components/Feed/Feed.tsx
  src/app/components/MatchItem/MatchItem.tsx
  src/app/components/Welcome/Welcome.examples.tsx
  src/app/components/Welcome/Welcome.module.css
  src/app/components/Welcome/Welcome.tsx
  src/app/components/examples.ts
  src/app/hooks/useMatches.ts
  src/app/logo.svg
  src/app/utils/api.ts
  src/app/utils/styles.ts
  src/lib/router.ts
  src/server.ts
  src/types.ts
Labels: component, enhancement

#36 Creating overwolf profile component
  dist/overwolf/manifest.json
  src/app/components/Profile/Profile.example.tsx
  src/app/components/Profile/Profile.module.css
  src/app/components/Profile/Profile.tsx
  src/app/components/Profile/defaultAvatar.svg
  src/app/components/examples.ts
  src/app/hooks/user.ts
  src/app/utils/user.tsx
  src/types.ts
Labels: component

#39 Ads container
  dist/overwolf/manifest.json
  src/app/components/Ads/Ads.examples.tsx
  src/app/components/Ads/Ads.module.css
  src/app/components/Ads/Ads.tsx
  src/app/components/examples.ts
  src/app/global.d.ts
Labels: component

#44 ✨ Display user in app
  src/app/App.tsx
  src/app/components/User/User.example.tsx
  src/app/components/User/User.module.css
  src/app/components/User/User.tsx
  src/app/components/User/defaultAvatar.svg
  src/app/components/examples.ts
Labels: component

#45 🔒️ Set CORS headers
  src/server.ts
Labels: security

#38 ✨ Auto post matches and match highlights into db
  README.md
  dist/overwolf/manifest.json
  package-lock.json
  package.json
  src/app/App.tsx
  src/app/components/Feed/Feed.tsx
  src/app/components/MatchDetails/MatchDetails.examples.tsx
  src/app/components/MatchDetails/MatchDetails.tsx
  src/app/components/MatchItem/MatchItem.examples.tsx
  src/app/components/MatchItem/MatchItem.tsx
  src/app/hooks/useMatches.ts
  src/app/utils/api.ts
  src/app/utils/games.ts
  src/app/utils/highlights.ts
  src/lib/router.ts
  src/types.ts
Labels: enhancement

#47 🚑 Allow all request origins in development
  src/server.ts
Labels: bug, development

#46 🚑 Remove block_top_window_navigation
  dist/overwolf/manifest.json
Labels: bug

#50 💄Implement base design
  src/app/App.module.css
  src/app/App.tsx
  src/app/components/Ads/Ads.module.css
  src/app/components/AppHeader/AppHeader.module.css
  src/app/components/Button/Button.examples.tsx
  src/app/components/Button/Button.module.css
  src/app/components/Button/Button.tsx
  src/app/components/Feed/Feed.tsx
  src/app/components/HardwareInfo/HardwareInfo.examples.tsx
  src/app/components/HardwareInfo/HardwareInfo.module.css
  src/app/components/HardwareInfo/HardwareInfo.tsx
  src/app/components/MatchDetails/MatchDetails.module.css
  src/app/components/MatchItem/MatchItem.module.css
  src/app/components/examples.ts
  src/app/globals.css
Labels: ui/ux

#49 ✨ Reactive matches in feed and details page
  samples.http
  src/app/App.tsx
  src/app/components/Feed/Feed.tsx
  src/app/components/MatchDetails/MatchDetails.examples.tsx
  src/app/components/MatchDetails/MatchDetails.tsx
  src/app/hooks/useFetch.ts
  src/app/hooks/useGameInfo.ts
  src/app/hooks/useMatches.ts
  src/app/utils/api.ts
  src/app/utils/highlights.ts
  src/lib/router.ts
Labels: enhancement

#54 🐛 Create BLOB from Array Buffer
  src/app/utils/highlights.ts
Labels: bug

#53 Remove flickering of login in the first place
  src/app/components/User/User.module.css
  src/app/components/User/User.tsx
  src/app/hooks/useCurrentUser.ts
  src/app/hooks/user.ts
Labels: bug

#64 🍱 Add logo
  src/app/components/AppHeader/AppHeader.module.css
  src/app/components/AppHeader/AppHeader.tsx
  src/app/components/AppHeader/logo.png
Labels: component

#63 ✨ Show stats in user component
  src/app/App.tsx
  src/app/components/Avatar/Avatar.examples.tsx
  src/app/components/Avatar/Avatar.module.css
  src/app/components/Avatar/Avatar.tsx
  src/app/components/User/User.example.tsx
  src/app/components/User/User.module.css
  src/app/components/User/User.tsx
  src/app/components/User/defaultAvatar.png
  src/app/components/User/defaultAvatar.svg
  src/app/components/examples.ts
  src/app/globals.css
Labels: component

#66 💄Apply Design Guide
  src/app/components/Ads/Ads.module.css
  src/app/components/AppHeader/AppHeader.module.css
  src/app/components/MatchDetails/MatchDetails.module.css
  src/app/components/MatchItem/MatchItem.module.css
  src/app/globals.css
Labels: ui/ux

#72 💄 Apply design guide styling
  src/app/components/AppHeader/AppHeader.module.css
  src/app/components/AppHeader/AppHeader.tsx
  src/app/components/MatchItem/MatchItem.module.css
  src/app/components/User/User.module.css
  src/app/components/User/User.tsx
  src/app/globals.css
Labels: ui/ux

#70 ✨ Add Highlight component
  src/app/components/Highlight/Highlight.examples.tsx
  src/app/components/Highlight/Highlight.module.css
  src/app/components/Highlight/Highlight.tsx
  src/app/components/Highlight/comment.png
  src/app/components/Highlight/like.png
  src/app/components/Highlight/share.png
  src/app/components/SummaryHighlightItem/SummaryHighlightItem.examples.tsx
  src/app/components/SummaryHighlightItem/SummaryHighlightItem.module.css
  src/app/components/SummaryHighlightItem/SummaryHighlightItem.tsx
  src/app/components/SummaryHighlightsFeed/SummaryHighlightsFeed.examples.tsx
  src/app/components/SummaryHighlightsFeed/SummaryHighlightsFeed.tsx
  src/app/components/User/User.module.css
  src/app/components/User/User.tsx
  src/app/components/UserInfo/UserInfo.example.tsx
  src/app/components/UserInfo/UserInfo.module.css
  src/app/components/UserInfo/UserInfo.tsx
  src/app/components/VideoHighlight/VideoHighlight.module.css
  src/app/components/VideoHighlight/VideoHighlight.tsx
  src/app/components/examples.ts
  src/app/utils/dates.ts
Labels: component

#78 ✨ Add feed filter and restyle feed
  src/app/components/Feed/Feed.module.css
  src/app/components/Feed/Feed.tsx
  src/app/components/FeedFilter/FeedFilter.module.css
  src/app/components/FeedFilterElement/FeedFilterElement.module.css
  src/app/components/MatchDetails/MatchDetails.tsx
  src/app/globals.css
Labels: component
